title = "Federação Paulista de Voo Livre"
baseURL = "https://ibombonato.github.io/fpvl/"
languageCode = "pt-br"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "br"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
mainSections = "noticias"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  logo = "/fpvl/images/fpvl.webp"
  org_name = "Federação Paulista de Voo Livre"
  favicon = ""
  description = "Federação Paulista de Voo Livre"
  facebook = "https://www.facebook.com/federacaopaulistadevoolivre/"
  twitter = ""
  instagram = "https://www.instagram.com/federacaopaulistadevoolivre/"
  youtube = "https://www.youtube.com/channel/UC30j1xMZVfvoeWMaySNrInA"
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/images/home.jpg"
  recent_posts_number = 2

[markup.goldmark.renderer]
unsafe= true

[menu]
  [[menu.main]]
      name = "Notícias"
      url = "/noticias/"
      weight = 1
  [[menu.main]]
      name = "Eventos"
      url = "/eventos/"
      weight = 2
  [[menu.main]]
      name = "Resultados"
      url = "/resultados/"
      weight = 3
  [[menu.main]]
      name = "Sobre"
      url = "/sobre/"
      weight = 5
  [[menu.main]]
      name = "Contato"
      url = "/contato/"
      weight = 6