name: Push Public to Deploy Repo

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test folder
      uses: crykn/copy_folder_to_another_repo_action@v1.0.5
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'public'
        destination_repo: 'ibombonato/fpvl'
        destination_folder: '.'
        user_email: 'action@github.com'
        user_name: 'GitHub Action'
        commit_msg: '[GHA] Deploy from source.'
