name: Create Docs Folder to Github pages

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        shopt -s extglob
        cd docs/
        rm -v !("CNAME") -r
        cd ..
        cp public/* docs/ -r
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Creating Docs Folder" --allow-empty
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    - name: Pushes docs folder
      uses: crykn/copy_folder_to_another_repo_action@v1.0.5
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'docs'
        destination_repo: 'ibombonato/fpvl'
        destination_folder: 'docs'
        user_email: 'action@github.com'
        user_name: 'GitHub Action'
        commit_msg: '[GHA] Update files.'
